#!/usr/bin/env python3
"""
site-scanner — a site hygiene crawler that anyone can run.

Crawls every page in a site's sitemap and reports the things people actually ask
about: missing alt text, oversized and broken images, broken links, duplicate
content, and duplicate or missing titles, H1s and meta descriptions.

Writes a self-contained HTML report anyone can open, a CSV with one column per
element, and optionally a JSON of raw facts for another tool to consume.

Standard library only. No install, no API keys, no JavaScript rendering.

    python site_scan.py example.com
    python site_scan.py example.com --limit 50
    python site_scan.py example.com --no-external      # skip outbound link checks
    python site_scan.py example.com --image-kb 150     # looser image budget
    python site_scan.py example.com --delay 0.5        # gentler on a small host

There is a window version too — see scanner_gui.py.
"""

import argparse
import concurrent.futures
import csv
import gzip
import hashlib
import json
import math
import html
import os
import re
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from html.parser import HTMLParser

UA = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
}
TIMEOUT = 30
SITEMAP_CANDIDATES = ["sitemap_index.xml", "wp-sitemap.xml", "sitemap.xml"]

# Thresholds. Every one of these is arguable; they are CLI flags for that reason.
# 100KB for a content image is a common performance budget, with 150-200KB
# tolerated for full-width banners that cannot compress further.
IMAGE_KB = 100          # an image heavier than this gets flagged
BANNER_KB = 200         # ...unless it is a banner/hero, which is allowed more
IMAGE_KB_BAD = 1000     # ...and heavier than this is called out as severe

# Banners and heroes are unavoidably large. Flagging them alongside a 400KB
# headshot buries the fixable problem in the unfixable one.
BANNER_HINTS = ("banner", "hero", "slider", "slide", "header", "background",
                "bg-", "-bg", "cover", "masthead", "carousel")
TITLE_MIN, TITLE_MAX = 30, 65
DESC_MIN, DESC_MAX = 70, 160
THIN_WORDS = 250        # below this, a page is thin enough to mention
DUPE_RATIO = 0.90       # shingle overlap at which two pages are "duplicate"
# Chrome is near-universal: the nav is on ~100% of pages. Setting this at 60%
# meant a cluster of templated city pages counted as boilerplate, got stripped,
# and vanished from the very check meant to catch it.
BOILERPLATE_AT = 0.90
BOILERPLATE_MIN = 10    # below this many pages, "on 90% of pages" means nothing
MIN_UNIQUE = 5          # shingles left after stripping, below which we use raw text

DECORATIVE_HINTS = ("spacer", "divider", "blank", "transparent", "1x1", "pixel")

# Blog titles and descriptions are usually generated by the platform, which
# appends the site name to every post and blows past any sane length limit. On
# one real 123-page site that was 73 of 115 title findings — enough noise to get
# the whole report dismissed. So blog rows are labelled and counted separately
# rather than dropped.
#
# Deliberately a coarse URL test: proper page-role classification needs more
# signal than a path, and belongs in whatever consumes this, not here.
# Whole path segments, not substrings — "/blogger-outreach" is a landing page,
# and a substring test would call it a blog post.
BLOG_PATH_SEGMENTS = frozenset((
    "blog", "blogs", "news", "post", "posts", "article", "articles", "insights"))
BLOG_DATE_RE = re.compile(r"/(19|20)\d{2}/\d{1,2}/")


# ---------------------------------------------------------------- fetching

class Resp(object):
    """One HTTP result. Never raises; failures come back with .error set."""

    def __init__(self, url, status=None, body="", final_url=None,
                 length=None, ctype="", error=None):
        self.url = url
        self.status = status
        self.body = body
        self.final_url = final_url or url
        self.length = length
        self.ctype = ctype
        self.error = error

    @property
    def ok(self):
        return self.error is None and self.status is not None and self.status < 400

    @property
    def redirected(self):
        return self.final_url.rstrip("/") != self.url.rstrip("/")

    @property
    def throttled(self):
        """Rate-limited, so its real status is unknown.

        Kept distinct from broken on purpose: "we could not check this" and
        "this is dead" are different claims and only one of them is work.
        """
        return self.status in THROTTLE_STATUS


def safe_url(url):
    """Make a URL sendable: IDNA for the host, percent-encoding for the rest.

    Real sites link to files with en-dashes and accented characters in the
    filename. urllib refuses those outright, and the resulting UnicodeEncodeError
    reads exactly like a broken link — a false finding, which is worse than a
    missed one. '%' is in the safe set so already-encoded URLs survive untouched.
    """
    try:
        parts = urllib.parse.urlsplit(url)
    except ValueError:
        return url
    host = parts.hostname or ""
    try:
        host = host.encode("idna").decode("ascii")
    except Exception:
        pass
    netloc = "%s:%d" % (host, parts.port) if parts.port else host
    if parts.username:
        cred = parts.username + ((":" + parts.password) if parts.password else "")
        netloc = cred + "@" + netloc
    path = urllib.parse.quote(parts.path, safe="/%:@&=+$,;~!*'()[]")
    query = urllib.parse.quote(parts.query, safe="/%:@&=+$,;?~!*'()[]")
    return urllib.parse.urlunsplit((parts.scheme, netloc, path, query, ""))


def _request(url, method="GET", timeout=TIMEOUT, extra_headers=None):
    headers = dict(UA)
    if extra_headers:
        headers.update(extra_headers)
    LIMITER.wait(url)
    req = urllib.request.Request(safe_url(url), headers=headers, method=method)
    return urllib.request.urlopen(req, timeout=timeout)


def fetch(url, timeout=TIMEOUT, read_body=True):
    """GET a URL, transparently gunzipping. Returns a Resp, never raises."""
    try:
        with _request(url, "GET", timeout) as r:
            raw = r.read() if read_body else b""
            if r.headers.get("Content-Encoding") == "gzip" or url.endswith(".gz"):
                try:
                    raw = gzip.decompress(raw)
                except OSError:
                    pass
            return Resp(
                url,
                status=r.status,
                body=raw.decode("utf-8", "replace") if read_body else "",
                final_url=r.geturl(),
                length=len(raw) if read_body else _int(r.headers.get("Content-Length")),
                ctype=(r.headers.get("Content-Type") or "").split(";")[0].strip().lower(),
            )
    except urllib.error.HTTPError as e:
        # A 404 is a result, not a failure — we are here to find them.
        return Resp(url, status=e.code, final_url=getattr(e, "url", url) or url,
                    ctype=(e.headers.get("Content-Type") or "").split(";")[0].strip().lower()
                    if e.headers else "")
    except Exception as e:
        return Resp(url, error=_short_err(e))


# "Come back later", not "gone". Squarespace and most CDNs throttle a fast
# crawler with these, and reporting a client's working page as a broken link
# because we hammered it is the worst kind of false positive — it sends someone
# to fix a page that was never broken.
#
# This is not hypothetical. An early version at 6 workers with no pacing had
# Squarespace return 429 for /trauma-therapy, a live page linked from 398 others,
# and the report called it a broken link.
RETRY_STATUS = frozenset((408, 425, 429, 500, 502, 503, 504))
THROTTLE_STATUS = frozenset((429, 503))
RETRY_WAIT = 2.0
MAX_RETRIES = 3
CRAWL_DELAY = 0.2       # seconds between requests to one host, ~5/s
MAX_BACKOFF = 30.0


class HostLimiter(object):
    """Spaces requests to a single host, however many threads are running.

    Worker count controls how many hosts we talk to at once; this controls how
    hard we lean on any one of them. Without it, concurrency and politeness are
    the same dial and you cannot raise one without losing the other.
    """

    def __init__(self, delay=CRAWL_DELAY):
        self.delay = delay
        self._next = {}
        self._lock = threading.Lock()

    def wait(self, url):
        if self.delay <= 0:
            return
        host = urllib.parse.urlparse(url).netloc.lower()
        with self._lock:
            now = time.monotonic()
            due = self._next.get(host, 0.0)
            sleep_for = max(0.0, due - now)
            self._next[host] = max(now, due) + self.delay
        if sleep_for:
            time.sleep(min(sleep_for, MAX_BACKOFF))


LIMITER = HostLimiter()


def retry_after(headers, attempt):
    """Honour Retry-After when the server sends one, else exponential backoff."""
    if headers:
        raw = headers.get("Retry-After")
        if raw:
            try:
                return min(float(raw), MAX_BACKOFF)
            except (TypeError, ValueError):
                pass
    return min(RETRY_WAIT * (2 ** attempt), MAX_BACKOFF)


def probe(url, timeout=15, _attempt=0):
    """HEAD a URL for status + size, falling back to a ranged GET.

    Plenty of hosts (and most CDNs fronting images) either reject HEAD outright
    or answer it without Content-Length, so the fallback is not optional.

    Throttling responses are retried once after a pause; see RETRY_STATUS.
    """
    try:
        with _request(url, "HEAD", timeout) as r:
            length = _int(r.headers.get("Content-Length"))
            ctype = (r.headers.get("Content-Type") or "").split(";")[0].strip().lower()
            if length is not None:
                return Resp(url, status=r.status, final_url=r.geturl(),
                            length=length, ctype=ctype)
            head = Resp(url, status=r.status, final_url=r.geturl(), ctype=ctype)
    except urllib.error.HTTPError as e:
        if e.code in (403, 405, 501):      # HEAD refused; try a real GET
            head = None
        elif e.code in RETRY_STATUS and _attempt < MAX_RETRIES:
            # Throttling arrives here, on the HEAD — this is the branch a 429
            # actually takes, so retrying only after the GET fallback never fires.
            time.sleep(retry_after(e.headers, _attempt))
            return probe(url, timeout=timeout, _attempt=_attempt + 1)
        else:
            return Resp(url, status=e.code, final_url=getattr(e, "url", url) or url)
    except Exception as e:
        head = Resp(url, error=_short_err(e))

    got = fetch(url, timeout=timeout, read_body=True)
    result = got if (got.ok or head is None or head.error) else head
    if result.status in RETRY_STATUS and _attempt < MAX_RETRIES:
        time.sleep(retry_after(None, _attempt))
        return probe(url, timeout=timeout, _attempt=_attempt + 1)
    return result


def _int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def _short_err(e):
    msg = str(e) or e.__class__.__name__
    return msg[:120]


class StatusCache(object):
    """Check each distinct URL once, however many pages link to it.

    On a therapy site the header nav is on all 300 pages. Without this the
    scan is 300x slower and hammers the client's server for no new information.
    """

    def __init__(self):
        self._done = {}
        self._locks = {}
        self._guard = threading.Lock()

    def get(self, url, fn):
        with self._guard:
            if url in self._done:
                return self._done[url]
            lock = self._locks.setdefault(url, threading.Lock())
        with lock:
            if url in self._done:
                return self._done[url]
            result = fn(url)
            with self._guard:
                self._done[url] = result
                self._locks.pop(url, None)
            return result

    def __len__(self):
        return len(self._done)


# ---------------------------------------------------------------- sitemap

def find_sitemap(base):
    for name in SITEMAP_CANDIDATES:
        r = fetch("%s/%s" % (base, name))
        if r.ok and ("<loc>" in r.body or "<sitemapindex" in r.body or "<urlset" in r.body):
            return r.url, r.body
    return None, None


def collect_urls(base, verbose=True):
    """Every page URL in the sitemap, following nested sitemap indexes."""
    start, body = find_sitemap(base)
    if not start:
        return [], None

    if verbose:
        print("Sitemap          : %s" % start)

    locs = re.findall(r"<loc>\s*(.*?)\s*</loc>", body)
    pages, children = [], []
    if "<sitemapindex" in body:
        children = locs
    else:
        pages = locs

    for child in children:
        if re.search(r"(image|video|news)[-_]?sitemap|sitemap[-_]?(image|video|news)",
                     child, re.I):
            continue        # media sitemaps list assets, not pages
        r = fetch(child)
        if not r.ok:
            print("  ! could not read %s (%s)" % (child, r.error or r.status))
            continue
        pages += re.findall(r"<loc>\s*(.*?)\s*</loc>", r.body)

    seen, out = set(), []
    for u in pages:
        u = html.unescape(u.strip())
        if u and u not in seen:
            seen.add(u)
            out.append(u)
    return out, start


# ---------------------------------------------------------------- parsing

SKIP_TEXT_IN = {"script", "style", "noscript", "template", "svg"}
# Chrome, footers, and legal boilerplate are not the page's content.
STRIP_CONTAINERS = {"nav", "header", "footer", "aside"}


class PageParser(HTMLParser):
    """Pull the on-page facts out of raw HTML with a real parser.

    Regex is fine for a canonical tag. It is not fine for images and links,
    where attribute order, self-closing forms, and stray quotes all vary.
    """

    def __init__(self):
        HTMLParser.__init__(self, convert_charrefs=True)
        self.title = None
        self.meta_desc = None
        self.meta_robots = ""
        self.canonical = None
        self.lang = None
        self.h1s = []
        self.images = []      # dicts: src, alt, alt_missing, width, height, decorative
        self.links = []       # dicts: href, anchor, rel, nofollow
        self._text = []
        self._skip_depth = 0
        self._chrome_depth = 0
        self._in_title = False
        self._h1_buf = None
        self._a_buf = None
        self._a_attrs = None

    # -- helpers
    @staticmethod
    def _d(attrs):
        return {k.lower(): (v or "") for k, v in attrs}

    def _start(self, tag, attrs):
        a = self._d(attrs)

        if tag in SKIP_TEXT_IN:
            self._skip_depth += 1
            return
        if tag in STRIP_CONTAINERS:
            self._chrome_depth += 1

        if tag == "html" and a.get("lang"):
            self.lang = a["lang"].strip()

        elif tag == "title":
            self._in_title = True

        elif tag == "meta":
            name = (a.get("name") or a.get("property") or "").lower()
            if name == "description" and self.meta_desc is None:
                self.meta_desc = a.get("content", "").strip()
            elif name == "robots":
                self.meta_robots = a.get("content", "").lower()

        elif tag == "link":
            rels = a.get("rel", "").lower().split()
            if "canonical" in rels and not self.canonical:
                self.canonical = a.get("href", "").strip()

        elif tag == "h1":
            self._h1_buf = []

        elif tag == "img":
            src = (a.get("src") or a.get("data-src") or a.get("data-lazy-src") or "").strip()
            if src and not src.startswith("data:"):
                alt = a.get("alt")
                self.images.append({
                    "src": src,
                    "alt": (alt or "").strip(),
                    # alt="" is a deliberate "this is decorative" and is correct.
                    # A missing alt attribute is the actual defect.
                    "alt_missing": alt is None,
                    "alt_empty": alt is not None and not alt.strip(),
                    "width": a.get("width", ""),
                    "height": a.get("height", ""),
                    "decorative": any(h in src.lower() for h in DECORATIVE_HINTS),
                    "lazy": "loading" in a and a.get("loading", "").lower() == "lazy",
                })

        elif tag == "a":
            self._a_attrs = a
            self._a_buf = []

    def handle_starttag(self, tag, attrs):
        self._start(tag.lower(), attrs)

    def handle_startendtag(self, tag, attrs):
        tag = tag.lower()
        if tag in SKIP_TEXT_IN or tag in STRIP_CONTAINERS:
            return          # self-closing, so it opens and shuts nothing
        self._start(tag, attrs)

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag in SKIP_TEXT_IN:
            self._skip_depth = max(0, self._skip_depth - 1)
        elif tag in STRIP_CONTAINERS:
            self._chrome_depth = max(0, self._chrome_depth - 1)
        elif tag == "title":
            self._in_title = False
        elif tag == "h1" and self._h1_buf is not None:
            h = " ".join("".join(self._h1_buf).split())
            if h:
                self.h1s.append(h)
            self._h1_buf = None
        elif tag == "a" and self._a_attrs is not None:
            href = (self._a_attrs.get("href") or "").strip()
            rel = self._a_attrs.get("rel", "").lower()
            if href:
                self.links.append({
                    "href": href,
                    "anchor": " ".join("".join(self._a_buf or []).split())[:120],
                    "rel": rel,
                    "nofollow": "nofollow" in rel,
                })
            self._a_attrs, self._a_buf = None, None

    def handle_data(self, data):
        if self._in_title:
            self.title = ((self.title or "") + data).strip()
            return
        if self._skip_depth:
            return
        if self._h1_buf is not None:
            self._h1_buf.append(data)
        if self._a_buf is not None:
            self._a_buf.append(data)
        if not self._chrome_depth:
            self._text.append(data)

    @property
    def text(self):
        return " ".join(" ".join(self._text).split())


def parse_page(body):
    p = PageParser()
    try:
        p.feed(body)
        p.close()
    except Exception:
        pass        # a malformed page still yields whatever parsed before the break
    return p


# ---------------------------------------------------------------- duplicates

WORD_RE = re.compile(r"[a-z0-9']+")
SHINGLE_N = 6

# Shingles catch pages that share PHRASES. They score ~0 on two pages that say
# the same thing in different words — which is the more common and more damaging
# case: two pages built for the same topic, competing with each other.
#
# TF-IDF cosine over single terms catches that middle band with no model and no
# API key. It does not do synonymy: "worry" and "anxiety" are unrelated tokens
# here. Real embeddings would catch that, at the cost of an API key and a
# per-crawl charge — see README.
# Calibrated against a 122-page site with five templated location pages. Those
# scored 58-68% against each other; the highest unrelated pair was terms-of-service
# vs privacy-policy at 35%, and two genuinely different service pages scored 34%.
# 0.50 sits in the gap with margin on both sides.
TOPIC_RATIO = 0.50      # cosine above which two pages are "the same topic"
TOPIC_MIN_TERMS = 40    # too few distinct terms and cosine is meaningless

# Small closed-class list. Not a full stopword set — TF-IDF already discounts
# anything common across the corpus. This just removes the words so frequent
# that they distort short pages.
STOPWORDS = frozenset("""
a an and are as at be been but by can do does for from had has have he her his
how i if in into is it its me my no not of on or our out she so than that the
their them then there these they this to too us was we were what when where
which who will with would you your about after all also any because before
being between both during each few more most other over same some such through
under until up very via while
""".split())


def shingles(text):
    """Set of overlapping 6-word phrases. Order-sensitive, cheap, good enough."""
    words = WORD_RE.findall(text.lower())
    if len(words) < SHINGLE_N:
        return set()
    return {
        hash(" ".join(words[i:i + SHINGLE_N]))
        for i in range(len(words) - SHINGLE_N + 1)
    }


def terms_of(text):
    """Bag of meaningful terms for TF-IDF. Counter of word -> frequency."""
    return Counter(w for w in WORD_RE.findall(text.lower())
                   if len(w) > 2 and w not in STOPWORDS)


def tfidf_vectors(pages):
    """L2-normalised TF-IDF vector per page, as {term: weight}.

    Normalising means cosine is a plain dot product, so the pair loop stays
    cheap: iterate the shorter vector and look up the longer one.
    """
    n = len(pages)
    doc_freq = Counter()
    for p in pages:
        doc_freq.update(p["terms"].keys())

    vectors = []
    for p in pages:
        vec = {}
        for term, tf in p["terms"].items():
            df = doc_freq[term]
            # No hard exclusion for terms on every page. An earlier version
            # dropped df == n as "navigation", which meant a corpus made mostly
            # of one template erased its own shared vocabulary and scored 0.0 —
            # the same self-erasure already fixed in the shingle path, and it
            # only failed on the small multi-location sites that need it most.
            # Smoothed IDF already handles it: df == n gives log(2), a real but
            # small weight, which is exactly the intent.
            #
            # Sublinear TF so one word repeated 50 times cannot dominate.
            vec[term] = (1.0 + math.log(tf)) * math.log(1.0 + n / float(df))
        norm = math.sqrt(sum(w * w for w in vec.values()))
        vectors.append({t: w / norm for t, w in vec.items()} if norm else {})
    return vectors


def cosine(a, b):
    if len(a) > len(b):
        a, b = b, a
    return sum(w * b.get(t, 0.0) for t, w in a.items())


def find_topic_overlap(pages, threshold=TOPIC_RATIO, include_blog=False):
    """Pages covering the same topic in different words.

    Returns [(page_a, page_b, score)] sorted by score. These are CANDIDATES to
    review, not proven cannibalisation — two pages can rank for different
    queries and both earn their traffic, and merging them destroys one. Proving
    competition needs a live SERP check this tool does not do.
    """
    live = [p for p in pages if len(p.get("terms") or ()) >= TOPIC_MIN_TERMS]
    if len(live) < 2:
        return []

    vectors = tfidf_vectors(live)
    out = []
    for i, a in enumerate(live):
        for j in range(i + 1, len(live)):
            b = live[j]
            # Two blog posts about anxiety are expected on a content site and
            # would swamp the finding. Pairs involving a non-blog page are the
            # ones worth a look.
            if not include_blog and is_blog(a["url"]) and is_blog(b["url"]):
                continue
            score = cosine(vectors[i], vectors[j])
            if score >= threshold:
                out.append((a, b, score))
    out.sort(key=lambda t: -t[2])
    return out


def topic_clusters(pages, threshold=TOPIC_RATIO, include_blog=False):
    """Group overlapping pages into sets, not pairs.

    Five templated location pages produce ten pairs, which reads as ten problems
    when it is one: a page template reused across five towns. Connected
    components over the pair graph collapse that into a single row naming all
    five. Returns [(sorted_urls, low_score, high_score)].
    """
    pairs = find_topic_overlap(pages, threshold, include_blog)
    if not pairs:
        return []

    adjacent = defaultdict(set)
    scores = {}
    for a, b, s in pairs:
        adjacent[a["url"]].add(b["url"])
        adjacent[b["url"]].add(a["url"])
        scores[frozenset((a["url"], b["url"]))] = s

    clusters, seen = [], set()
    for start in sorted(adjacent):
        if start in seen:
            continue
        # Breadth-first walk of one connected component.
        members, queue = set(), [start]
        while queue:
            node = queue.pop()
            if node in members:
                continue
            members.add(node)
            queue.extend(adjacent[node] - members)
        seen |= members

        inside = [s for pair, s in scores.items() if pair <= members]
        clusters.append((sorted(members), min(inside), max(inside)))

    clusters.sort(key=lambda c: (-len(c[0]), -c[2]))
    return clusters


GOLDEN_ANGLE = 2.399963229728653
MAP_EDGE_FLOOR = 0.22   # below this, an edge says nothing
MAP_EDGES_PER_NODE = 3  # keep each page's strongest few; a dense hairball reads as noise


NEIGHBOURS_PER_PAGE = 3


def similarity_graph(pages, floor=MAP_EDGE_FLOOR, per_node=MAP_EDGES_PER_NODE):
    """Returns (nodes, edges, neighbours), all by TF-IDF cosine.

    Every pair above the floor would be a hairball on a 120-page site, so the
    drawn edges keep only each page's strongest few links. `neighbours` is the
    same data unpruned to a per-page top-N, because "what is this page closest
    to" is the question a reader actually has, and it should not be answerable
    only for the pages that happened to get flagged.

    The cosine loop is the expensive part of a scan, so both come out of one
    pass rather than being recomputed.
    """
    live = [p for p in pages if len(p.get("terms") or ()) >= TOPIC_MIN_TERMS]
    if len(live) < 3:
        return [], [], {}

    vectors = tfidf_vectors(live)
    best = defaultdict(list)
    for i in range(len(live)):
        for j in range(i + 1, len(live)):
            score = cosine(vectors[i], vectors[j])
            if score >= floor:
                best[i].append((score, j))
                best[j].append((score, i))

    edges, neighbours = {}, {}
    for i, candidates in best.items():
        candidates.sort(reverse=True)
        neighbours[i] = candidates[:NEIGHBOURS_PER_PAGE]
        for score, j in candidates[:per_node]:
            edges[frozenset((i, j))] = score
    return (live,
            [(min(p), max(p), s) for p, s in
             sorted(edges.items(), key=lambda kv: kv[1])],
            neighbours)


LAYOUT_SPAN = 1000.0
LAYOUT_GRAVITY = 1.0    # 1.0 puts equilibrium at about the domain radius


def layout_force(node_count, edges, iterations=300):
    """Fruchterman-Reingold spring layout. Deterministic — no RNG.

    Same site scanned twice must draw the same picture, or two runs cannot be
    compared. Initial placement is a golden-angle spiral for that reason.

    Two things this has to get right, both learned by looking at the output:

    - **Gravity is not optional.** Most pages on a real site share vocabulary
      with nothing, so they have no edges and feel only repulsion — which flings
      them to the boundary and draws a ring with everything interesting crushed
      in the middle. A pull toward the centre keeps unconnected pages in frame.
    - **Scale the domain, not the forces.** Working in a 1000-unit square with
      k = sqrt(area/n) puts the equilibrium edge length at k, where repulsion
      k^2/d and attraction d^2/k balance. In normalised 0-1 coordinates the same
      formulas overshoot on every step and the graph never settles.
    """
    if node_count < 1:
        return []

    centre = LAYOUT_SPAN / 2.0
    pos = []
    for i in range(node_count):
        radius = math.sqrt((i + 0.5) / node_count) * centre * 0.9
        angle = i * GOLDEN_ANGLE
        pos.append([centre + radius * math.cos(angle),
                    centre + radius * math.sin(angle)])

    k = math.sqrt((LAYOUT_SPAN * LAYOUT_SPAN) / node_count)
    temp = LAYOUT_SPAN / 8.0
    cooling = temp / (iterations + 1)
    min_dist = k * 0.01

    # Gravity has to balance repulsion, and total repulsion on one node grows
    # with node count: roughly n*k^2/R at radius R. Setting the inward pull to
    # n*k^2/centre^2 per unit of offset puts equilibrium near the domain radius.
    # Since k^2 = span^2/n, the n cancels and this is simply 4*LAYOUT_GRAVITY —
    # derived rather than tuned, which is why it holds at any page count.
    gravity = LAYOUT_GRAVITY * node_count * k * k / (centre * centre)

    for _ in range(iterations):
        disp = [[0.0, 0.0] for _ in range(node_count)]

        for i in range(node_count):
            xi, yi = pos[i]
            for j in range(i + 1, node_count):
                dx, dy = xi - pos[j][0], yi - pos[j][1]
                dist = math.sqrt(dx * dx + dy * dy)
                if dist < min_dist:
                    # Deterministic nudge apart, never a random one.
                    dx, dy = (i - j) or 1, (j - i) or 1
                    dist = math.sqrt(dx * dx + dy * dy)
                force = (k * k) / dist
                ux, uy = dx / dist, dy / dist
                disp[i][0] += ux * force
                disp[i][1] += uy * force
                disp[j][0] -= ux * force
                disp[j][1] -= uy * force

        for a, b, weight in edges:
            dx, dy = pos[a][0] - pos[b][0], pos[a][1] - pos[b][1]
            dist = math.sqrt(dx * dx + dy * dy) or min_dist
            # Similarity scales the spring, so closer really does mean more
            # alike — the one inference the reader may draw from distance.
            force = (dist * dist) / k * weight
            ux, uy = dx / dist, dy / dist
            disp[a][0] -= ux * force
            disp[a][1] -= uy * force
            disp[b][0] += ux * force
            disp[b][1] += uy * force

        for i in range(node_count):
            disp[i][0] += (centre - pos[i][0]) * gravity
            disp[i][1] += (centre - pos[i][1]) * gravity

            dx, dy = disp[i]
            length = math.sqrt(dx * dx + dy * dy)
            if length > 1e-12:
                step = min(length, temp) / length
                pos[i][0] += dx * step
                pos[i][1] += dy * step
        temp -= cooling

    return pos


def jaccard(a, b):
    if not a or not b:
        return 0.0
    inter = len(a & b)
    if not inter:
        return 0.0
    return inter / float(len(a | b))


def is_indexable(page):
    """Would Google index this page as itself?

    Screaming Frog restricts duplicate detection to indexable pages by default,
    and it is right to: a noindexed page, or one canonicalised to a different
    URL, has already been told not to compete. Flagging it as duplicate creates
    work that fixes nothing.
    """
    if page.get("noindex"):
        return False
    canon = (page.get("canonical") or "").strip()
    if canon:
        here = (page.get("final_url") or page.get("url") or "").rstrip("/")
        if canon.rstrip("/") != here:
            return False
    return True


def find_exact_duplicates(pages):
    """Byte-identical body text, grouped. Screaming Frog's 'Exact Duplicates'.

    Free — the hash is already computed during parsing — and worth separating
    from near-duplicates, because identical pages are an unambiguous defect
    while 91%-similar pages need a human to look.
    """
    by_hash = defaultdict(list)
    for p in pages:
        if p.get("text_hash") and p.get("words"):
            by_hash[p["text_hash"]].append(p)
    return [sorted(g, key=lambda p: p["url"])
            for g in by_hash.values() if len(g) > 1]


def find_duplicates(pages, threshold=DUPE_RATIO):
    """Group near-identical pages, after subtracting site-wide boilerplate.

    Without the boilerplate step every page on a template-driven site looks
    ~70% similar to every other and the check is noise. Any phrase appearing on
    more than BOILERPLATE_AT of pages is chrome the parser did not catch.
    """
    live = [p for p in pages if p.get("shingles")]
    if len(live) < 2:
        return [], 0

    boilerplate = set()
    if len(live) >= BOILERPLATE_MIN:
        counts = Counter()
        for p in live:
            counts.update(p["shingles"])
        cutoff = max(3, int(len(live) * BOILERPLATE_AT))
        boilerplate = {s for s, n in counts.items() if n >= cutoff}

    for p in live:
        stripped = p["shingles"] - boilerplate
        # A cluster of identical pages pushes its own content over the
        # boilerplate threshold and erases itself — which is how a set of
        # templated city pages, the exact thing worth catching, comes back
        # clean. When stripping leaves a page with nothing, compare its full
        # text instead: two pages identical after chrome removal are still
        # identical, and a page with no distinctive content is worth flagging
        # either way.
        p["unique_shingles"] = stripped if len(stripped) >= MIN_UNIQUE else p["shingles"]

    # Bucket by length first so we only compare pages that could plausibly match.
    live.sort(key=lambda p: len(p["unique_shingles"]))
    groups, claimed = [], set()

    for i, a in enumerate(live):
        if a["url"] in claimed or len(a["unique_shingles"]) < MIN_UNIQUE:
            continue
        cluster = []
        a_len = len(a["unique_shingles"])
        for b in live[i + 1:]:
            b_len = len(b["unique_shingles"])
            if b_len > a_len * 2:
                break                       # sorted, so nothing further can match
            if b["url"] in claimed:
                continue
            sim = jaccard(a["unique_shingles"], b["unique_shingles"])
            if sim >= threshold:
                cluster.append((b, sim))
        if cluster:
            claimed.add(a["url"])
            for b, _ in cluster:
                claimed.add(b["url"])
            groups.append({
                "primary": a,
                "matches": sorted(cluster, key=lambda t: -t[1]),
            })

    return groups, len(boilerplate)


# ---------------------------------------------------------------- checking

def is_blog(url):
    """Coarse: does this URL look like a blog post or archive page?

    The blog index itself counts — its meta is as templated as the posts'.
    """
    path = urllib.parse.urlparse(url).path.lower()
    if BLOG_DATE_RE.search(path.rstrip("/") + "/"):
        return True
    return any(seg in BLOG_PATH_SEGMENTS for seg in path.split("/") if seg)


def is_banner(url):
    """Does this image look like a banner or hero? Filename is all we have.

    Imperfect on purpose: the alternative is measuring rendered dimensions,
    which needs the browser we deliberately do not run.
    """
    name = urllib.parse.urlparse(url).path.lower()
    return any(h in name for h in BANNER_HINTS)


def content_split(pages):
    """Three buckets, as percentages: duplicate / common / unique.

    Clusters answer "which pages"; this answers "how much", which is the number
    people usually want to track over time. Both are worth having.

    A phrase on nearly every page is chrome ("common"). A phrase on a handful of
    pages but not all is real duplication. Everything else is unique. Siteliner
    reports the same three buckets, so the shape is deliberately familiar.
    """
    live = [p for p in pages if p.get("shingles")]
    if not live:
        return None

    counts = Counter()
    for p in live:
        counts.update(p["shingles"])
    common_at = max(3, int(len(live) * BOILERPLATE_AT)) if len(live) >= BOILERPLATE_MIN \
        else len(live) + 1      # too few pages to call anything chrome

    dup = com = uniq = 0
    for p in live:
        for s in p["shingles"]:
            n = counts[s]
            if n >= common_at:
                com += 1
            elif n > 1:
                dup += 1
            else:
                uniq += 1

    total = dup + com + uniq
    if not total:
        return None
    pct = lambda v: round(v * 100.0 / total, 1)
    return {
        "duplicate_pct": pct(dup), "common_pct": pct(com),
        "unique_pct": pct(uniq), "pages_measured": len(live),
        # Siteliner also separates chrome into a "Common Content" bucket, so
        # duplicate_pct is broadly comparable to its Duplicate Content figure and
        # a benchmark set against that one carries over. The other two do not:
        # this strips nav/header/footer/aside at parse time rather than bucketing
        # them, so common_pct lands near zero and unique_pct is correspondingly
        # inflated against a denominator that still includes chrome.
        "basis": "body text; nav/header/footer/aside removed at parse time",
        "duplicate_pct_comparable_to_siteliner": True,
        "unique_pct_comparable_to_siteliner": False,
    }


def norm_url(href, page_url):
    """Absolute, fragment-free URL. Returns None for non-http schemes."""
    href = html.unescape(href.strip())
    if not href or href.startswith("#"):
        return None
    low = href.lower()
    if low.startswith(("mailto:", "tel:", "javascript:", "data:", "sms:")):
        return None
    try:
        absolute = urllib.parse.urljoin(page_url, href)
    except ValueError:
        return None
    if not absolute.lower().startswith(("http://", "https://")):
        return None
    return urllib.parse.urldefrag(absolute)[0]


def scan_page(url, site_host, opts):
    """Fetch and parse one page. Link/image status checks happen later."""
    r = fetch(url)
    # A throttled page is not one missing row: every link and image on it drops
    # out of the crawl, so a 429 here quietly shrinks coverage and makes the
    # broken-link count differ between runs of the same site.
    attempt = 0
    while r.status in RETRY_STATUS and attempt < MAX_RETRIES:
        time.sleep(retry_after(None, attempt))
        r = fetch(url)
        attempt += 1
    page = {
        "url": url, "final_url": r.final_url, "status": r.status,
        "error": r.error, "redirected": r.redirected,
    }
    if not r.ok or "html" not in (r.ctype or "text/html"):
        page["skipped"] = not r.ok
        return page

    p = parse_page(r.body)
    text = p.text
    words = len(WORD_RE.findall(text))

    links, images = [], []
    for l in p.links:
        target = norm_url(l["href"], r.final_url)
        if target:
            links.append(dict(l, target=target,
                              internal=urllib.parse.urlparse(target).netloc.lower()
                              .replace("www.", "") == site_host))
    for im in p.images:
        target = norm_url(im["src"], r.final_url)
        if target:
            images.append(dict(im, target=target))

    page.update({
        "title": p.title or "",
        "meta_desc": p.meta_desc or "",
        "meta_robots": p.meta_robots,
        "canonical": p.canonical or "",
        "lang": p.lang or "",
        "h1s": p.h1s,
        "words": words,
        "text_hash": hashlib.sha1(text.encode("utf-8", "replace")).hexdigest(),
        "shingles": shingles(text),
        "terms": terms_of(text),
        "links": links,
        "images": images,
        "noindex": "noindex" in p.meta_robots,
    })
    return page


def check_assets(pages, cache, opts, progress=None):
    """Resolve every distinct link and image once, in parallel."""
    link_targets, image_targets = set(), set()
    for pg in pages:
        for l in pg.get("links", []):
            if l["internal"] or opts.external:
                link_targets.add(l["target"])
        for im in pg.get("images", []):
            image_targets.add(im["target"])

    todo = [(u, "link") for u in sorted(link_targets)]
    todo += [(u, "image") for u in sorted(image_targets - link_targets)]
    if not todo:
        return {}

    results, done = {}, [0]
    lock = threading.Lock()

    def one(item):
        url, kind = item
        res = cache.get(url, lambda u: probe(u, timeout=opts.timeout))
        with lock:
            results[url] = res
            done[0] += 1
            if progress and done[0] % 25 == 0:
                progress(done[0], len(todo))
        return res

    with concurrent.futures.ThreadPoolExecutor(max_workers=opts.workers) as ex:
        list(ex.map(one, todo))

    if progress:
        progress(len(todo), len(todo))
    return results


def build_findings(pages, assets, opts):
    """Turn raw page data into the issue lists the report renders."""
    live = [p for p in pages if p.get("status") and p["status"] < 400
            and not p.get("skipped") and "title" in p]

    f = defaultdict(list)

    # -- fetch failures
    for p in pages:
        if p.get("error"):
            f["unreachable"].append({"url": p["url"], "detail": p["error"],
                                     "text": p["error"]})
        elif p.get("status") and p["status"] >= 400:
            f["page_error"].append({"url": p["url"],
                                    "detail": "HTTP %s" % p["status"],
                                    "status": p["status"]})

    # -- titles, descriptions, H1s
    by_title, by_desc = defaultdict(list), defaultdict(list)
    for p in live:
        t, d = p["title"].strip(), p["meta_desc"].strip()
        if not t:
            f["title_missing"].append({"url": p["url"], "detail": ""})
        else:
            by_title[t.lower()].append(p["url"])
            for bucket, test in (("title_long", len(t) > TITLE_MAX),
                                 ("title_short", len(t) < TITLE_MIN)):
                if test:
                    f[bucket].append({
                        "url": p["url"], "detail": "%d chars — %s" % (len(t), t),
                        "value": len(t), "unit": "characters", "text": t})
        if not d:
            f["desc_missing"].append({"url": p["url"], "detail": ""})
        else:
            by_desc[d.lower()].append(p["url"])
            for bucket, test in (("desc_long", len(d) > DESC_MAX),
                                 ("desc_short", len(d) < DESC_MIN)):
                if test:
                    f[bucket].append({
                        "url": p["url"], "detail": "%d chars" % len(d),
                        "value": len(d), "unit": "characters", "text": d})

        if not p["h1s"]:
            f["h1_missing"].append({"url": p["url"], "detail": ""})
        elif len(p["h1s"]) > 1:
            f["h1_multiple"].append({
                "url": p["url"],
                "detail": "%d H1s — %s" % (len(p["h1s"]), " | ".join(p["h1s"][:3])),
                "value": len(p["h1s"]), "unit": "H1 tags",
                "text": " | ".join(p["h1s"][:5]),
            })
        if p["words"] < THIN_WORDS and not p.get("noindex"):
            f["thin"].append({"url": p["url"], "detail": "%d words" % p["words"],
                              "value": p["words"], "unit": "words"})

    for t, urls in by_title.items():
        if len(urls) > 1:
            f["title_duplicate"].append({
                "url": urls[0], "detail": "%d pages share this title" % len(urls),
                "group": urls[1:], "value": len(urls), "unit": "pages", "text": t,
            })
    for d, urls in by_desc.items():
        if len(urls) > 1:
            f["desc_duplicate"].append({
                "url": urls[0], "detail": "%d pages share this description" % len(urls),
                "group": urls[1:], "value": len(urls), "unit": "pages", "text": d,
            })

    # -- images
    seen_img = set()
    alt_missing, alt_empty = defaultdict(list), defaultdict(list)
    for p in live:
        for im in p["images"]:
            # Keyed by image, not by occurrence. One logo in the header is one
            # fix, not one fix per page — counting occurrences turns a 3-item
            # job into a 399-item wall nobody reads.
            if im["alt_missing"]:
                alt_missing[im["target"]].append(p["url"])
            elif im["alt_empty"] and not im["decorative"]:
                alt_empty[im["target"]].append(p["url"])

            if im["target"] in seen_img:
                continue
            seen_img.add(im["target"])
            res = assets.get(im["target"])
            if not res:
                continue
            if res.error or (res.status and res.status >= 400):
                f["image_broken"].append({
                    "url": im["target"],
                    "detail": "%s — first seen on %s" % (
                        res.error or "HTTP %s" % res.status, p["url"]),
                })
            elif res.length and res.length > IMAGE_KB_BAD * 1024:
                f["image_huge"].append({
                    "url": im["target"],
                    "detail": "%.1f MB — first seen on %s" % (
                        res.length / 1048576.0, p["url"]),
                    "kb": res.length // 1024,
                    "value": res.length // 1024, "unit": "KB",
                    "group": [p["url"]],
                    "sort": -res.length,
                })
            elif res.length:
                banner = is_banner(im["target"])
                budget = opts.banner_kb if banner else opts.image_kb
                if res.length > budget * 1024:
                    f["image_heavy"].append({
                        "url": im["target"],
                        "detail": "%d KB%s — first seen on %s" % (
                            res.length // 1024,
                            " (banner, budget %dKB)" % budget if banner else "",
                            p["url"]),
                        "kb": res.length // 1024,
                        "banner": banner,
                        "value": res.length // 1024, "unit": "KB",
                        "text": "banner" if banner else "",
                        "group": [p["url"]],
                        "sort": -res.length,
                    })

    for bucket, key in ((alt_missing, "alt_missing"), (alt_empty, "alt_empty")):
        for src, on_pages in bucket.items():
            f[key].append({
                "url": src,
                "detail": "on %d page%s (e.g. %s)" % (
                    len(on_pages), "" if len(on_pages) == 1 else "s", on_pages[0]),
                "group": on_pages,
                "value": len(on_pages), "unit": "pages",
                "sort": -len(on_pages),
            })
        f[key].sort(key=lambda r: r["sort"])

    for key in ("image_huge", "image_heavy"):
        f[key].sort(key=lambda r: r.get("sort", 0))

    # -- links
    broken = defaultdict(list)
    unverified = defaultdict(list)
    redirects = defaultdict(list)
    internal_targets = set()
    for p in live:
        for l in p["links"]:
            if not l["internal"] and not opts.external:
                continue
            res = assets.get(l["target"])
            if not res:
                continue
            if l["internal"]:
                internal_targets.add(l["target"])
            if res.throttled:
                # Still rate-limited after every retry. Its real status is
                # unknown, and "unknown" must never be published as "broken".
                unverified[l["target"]].append((p["url"], l["anchor"], res))
            elif res.error or (res.status and res.status >= 400):
                broken[l["target"]].append((p["url"], l["anchor"], res))
            elif l["internal"] and res.redirected and res.status and res.status < 400:
                redirects[l["target"]].append((p["url"], res.final_url))

    for target, hits in broken.items():
        res = hits[0][2]
        internal = target in internal_targets
        f["link_broken"].append({
            "url": target,
            # The two want different fixes: an internal 4xx gets a redirect, an
            # external one gets the link removed or repointed.
            "detail": "%s%s — linked from %d page%s (e.g. %s)" % (
                "internal, " if internal else "",
                res.error or "HTTP %s" % res.status,
                len(hits), "" if len(hits) == 1 else "s", hits[0][0]),
            "group": [h[0] for h in hits],
            "internal": internal,
            "status": res.status or (res.error or "")[:40],
            "value": len(hits), "unit": "pages linking",
            "text": "internal" if internal else "external",
            "sort": (0 if internal else 1, -len(hits)),
        })
    f["link_broken"].sort(key=lambda r: r["sort"])

    for target, hits in unverified.items():
        res = hits[0][2]
        f["link_unverified"].append({
            "url": target,
            "detail": "rate-limited (HTTP %s) after %d attempts — status unknown, "
                      "linked from %d page%s" % (
                          res.status, MAX_RETRIES + 1, len(hits),
                          "" if len(hits) == 1 else "s"),
            "group": [h[0] for h in hits],
            "internal": target in internal_targets,
            "status": res.status,
            "value": len(hits), "unit": "pages linking",
            "text": "status unknown — not confirmed broken",
            "sort": -len(hits),
        })
    f["link_unverified"].sort(key=lambda r: r["sort"])

    for target, hits in redirects.items():
        f["link_redirect"].append({
            "url": target,
            "detail": "-> %s — linked from %d page%s" % (
                hits[0][1], len(hits), "" if len(hits) == 1 else "s"),
            "group": [h[0] for h in hits],
            "sort": -len(hits),
        })
    f["link_redirect"].sort(key=lambda r: r["sort"])

    # Label the page-level meta findings by page type. Images and links are
    # deliberately NOT segmented: a broken link or a 2 MB image is a defect
    # wherever it lives, and tagging the blog-category 404s as "blog" would bury
    # the largest finding on a blog-heavy site.
    for key in BLOG_SEGMENTED:
        for r in f.get(key) or []:
            r["blog"] = is_blog(r["url"])
        if getattr(opts, "exclude_blog", False):
            f[key] = [r for r in f.get(key) or [] if not r["blog"]]

    # -- duplicate content, on indexable pages only (Screaming Frog's default)
    indexable = [p for p in live if is_indexable(p)]

    for g in find_exact_duplicates(indexable):
        f["content_exact"].append({
            "url": g[0]["url"],
            "detail": "identical to %d other page%s: %s" % (
                len(g) - 1, "" if len(g) == 2 else "s",
                ", ".join(p["url"] for p in g[1:4])),
            "group": [p["url"] for p in g[1:]],
            "value": len(g), "unit": "identical pages",
        })

    exact_seen = {u for r in f["content_exact"]
                  for u in [r["url"]] + r.get("group", [])}
    groups, boiler = find_duplicates(indexable, opts.dupe_ratio)
    for g in groups:
        # Already reported as byte-identical; don't say it twice.
        if g["primary"]["url"] in exact_seen:
            continue
        f["content_duplicate"].append({
            "url": g["primary"]["url"],
            "detail": "%d near-identical page%s: %s" % (
                len(g["matches"]), "" if len(g["matches"]) == 1 else "s",
                ", ".join("%s (%d%%)" % (b["url"], round(s * 100))
                          for b, s in g["matches"][:3])),
            "group": [b["url"] for b, _ in g["matches"]],
            "value": round(max(s for _, s in g["matches"]) * 100),
            "unit": "% similar",
        })

    # -- same topic, different words. Pairs already reported as duplicates would
    # only be said twice, so skip them.
    dupe_seen = {u for key in ("content_exact", "content_duplicate")
                 for r in f.get(key) or [] for u in [r["url"]] + r.get("group", [])}
    for members, low, high in topic_clusters(
            indexable, getattr(opts, "topic_ratio", TOPIC_RATIO),
            getattr(opts, "include_blog_topics", False)):
        if all(u in dupe_seen for u in members):
            continue
        head, rest = members[0], members[1:]
        f["content_topic"].append({
            "url": head,
            "detail": "%d pages share %d-%d%% of their vocabulary: %s" % (
                len(members), round(low * 100), round(high * 100),
                ", ".join(rest[:3]) + (", ..." if len(rest) > 3 else "")),
            "group": rest,
            "value": round(high * 100), "unit": "% term overlap",
            "text": "%d pages" % len(members),
        })

    return f, live, boiler


# ---------------------------------------------------------------- report

# key -> (severity, label, what to do about it)
ISSUES = [
    ("unreachable",       "high", "Pages that would not load",
     "The scanner could not fetch these at all. Usually a dead sitemap entry or a server timeout."),
    ("page_error",        "high", "Pages returning an error",
     "In the sitemap but serving 4xx/5xx. Remove from the sitemap or fix the page."),
    ("link_broken",       "high", "Broken links",
     "Point somewhere dead. Fix the href or remove the link."),
    ("image_broken",      "high", "Broken images",
     "The image file is missing. Re-upload or drop the reference."),
    ("alt_missing",       "high", "Images with no alt attribute",
     "Add descriptive alt text. Genuinely decorative images should have alt=\"\", not nothing."),
    ("content_exact",     "high", "Identical page content",
     "These pages have byte-identical body text. One should be consolidated or redirected."),
    ("content_duplicate", "high", "Near-duplicate page content",
     "At or above 90% similar after shared nav and footer are stripped — the same "
     "threshold Screaming Frog uses. Usually templated city pages. Consolidate or rewrite."),
    ("content_topic",     "med",  "Pages covering the same topic",
     "Different wording, heavily overlapping vocabulary — these may be built for "
     "the same search. CANDIDATES TO REVIEW, not proven competition: two pages "
     "can rank for different queries and both earn traffic, and merging them "
     "destroys one. Search each page's target term and see whether both actually "
     "appear before changing anything."),
    ("title_duplicate",   "med",  "Duplicate title tags",
     "Each page needs its own title. Duplicates usually mean a template is not filling in."),
    ("title_missing",     "high", "Missing title tags",
     "Every page needs a title tag."),
    ("h1_missing",        "med",  "Missing H1",
     "Add one H1 describing the page."),
    ("h1_multiple",       "low",  "More than one H1",
     "Usually a theme quirk. Worth a look, rarely urgent."),
    ("desc_missing",      "med",  "Missing meta description",
     "Google will write its own. Yours will be better."),
    ("desc_duplicate",    "med",  "Duplicate meta descriptions",
     "Same fix as duplicate titles."),
    ("image_huge",        "med",  "Images over 1 MB",
     "These are the page-speed problem. Resize and compress before re-uploading."),
    ("image_heavy",       "low",  "Oversized images",
     "Over the size budget. Compress when convenient."),
    ("alt_empty",         "low",  "Images with empty alt text",
     "alt=\"\" is correct for decorative images and wrong for meaningful ones. Check these."),
    ("link_unverified",   "med",  "Links that could not be checked",
     "The server rate-limited us, so these were never confirmed either way. Not "
     "known to be broken. Re-run with a longer --delay to check them properly."),
    ("link_redirect",     "low",  "Internal links pointing at a redirect",
     "Link straight to the final URL and save the hop."),
    ("title_long",        "low",  "Titles over %d characters" % TITLE_MAX,
     "Will be truncated in results."),
    ("title_short",       "low",  "Titles under %d characters" % TITLE_MIN,
     "Room to say more."),
    ("desc_long",         "low",  "Meta descriptions over %d characters" % DESC_MAX,
     "Will be truncated."),
    ("desc_short",        "low",  "Meta descriptions under %d characters" % DESC_MIN,
     "Room to say more."),
    ("thin",              "low",  "Thin pages",
     "Under %d words. Fine for a contact page, a problem for a landing page." % THIN_WORDS),
]

SEV_ORDER = {"high": 0, "med": 1, "low": 2}
SEV_LABEL = {"high": "High", "med": "Medium", "low": "Low"}

# Findings worth splitting by page type, because platform-generated blog meta
# would otherwise swamp the rows someone can actually act on.
BLOG_SEGMENTED = ("title_missing", "title_duplicate", "title_long", "title_short",
                  "desc_missing", "desc_duplicate", "desc_long", "desc_short",
                  "h1_missing", "h1_multiple", "thin")


def blog_split(rows):
    """(total, on_blog). Returns (n, 0) for findings that are not segmented."""
    return len(rows), sum(1 for r in rows if r.get("blog"))


def print_console(domain, findings, live, pages, elapsed, cache_size, split=None):
    print("")
    print("=" * 68)
    print("RESULTS  %s" % domain)
    print("=" * 68)
    print("  Pages crawled  : %d" % len(pages))
    print("  Pages parsed   : %d" % len(live))
    print("  URLs verified  : %d" % cache_size)
    print("  Elapsed        : %.0fs" % elapsed)
    print("")

    any_found = False
    for key, sev, label, _ in sorted(ISSUES, key=lambda i: SEV_ORDER[i[1]]):
        rows = findings.get(key) or []
        if not rows:
            continue
        any_found = True
        total, on_blog = blog_split(rows)
        note = "   (%d on blog posts)" % on_blog if on_blog else ""
        print("  [%-4s] %-42s %d%s" % (SEV_LABEL[sev], label, total, note))

    if split:
        print("")
        print("  Content: %s%% duplicate, %s%% shared chrome, %s%% unique"
              % (split["duplicate_pct"], split["common_pct"], split["unique_pct"]))
        # No % formatting on this line, so the percent signs are literal singles.
        print("           (duplicate % compares to Siteliner; unique % does not "
              "— chrome is stripped, not bucketed)")

    if not any_found:
        print("  Clean. Nothing found.")
        return

    print("")
    for key, sev, label, _ in sorted(ISSUES, key=lambda i: SEV_ORDER[i[1]]):
        rows = findings.get(key) or []
        if not rows or sev != "high":
            continue
        print("--- %s (%d) ---" % (label, len(rows)))
        for r in rows[:10]:
            print("  %s" % r["url"])
            if r.get("detail"):
                print("      %s" % r["detail"])
        if len(rows) > 10:
            print("  ... and %d more (see the report)" % (len(rows) - 10))
        print("")


CSV_COLUMNS = ["Severity", "Issue", "URL", "Page type", "Status", "Measurement",
               "Unit", "Content", "Pages affected", "Example page",
               "All affected pages"]


def write_csv(path, findings):
    """One row per finding, each element in its own column.

    Screaming Frog splits its data across typed columns but spreads it over
    thirty report tabs. This keeps the typed columns and puts everything on one
    sheet, so a PM filters by Issue and sorts by Measurement — images by KB,
    titles by length, broken links by how many pages point at them.
    """
    with open(path, "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.writer(fh)
        w.writerow(CSV_COLUMNS)
        for key, sev, label, _ in sorted(ISSUES, key=lambda i: SEV_ORDER[i[1]]):
            for r in findings.get(key) or []:
                group = r.get("group", [])
                w.writerow([
                    SEV_LABEL[sev],
                    label,
                    r["url"],
                    "blog" if r.get("blog") else "",
                    r.get("status", ""),
                    r.get("value", ""),
                    r.get("unit", ""),
                    r.get("text", ""),
                    len(group) if group else "",
                    group[0] if group else "",
                    " | ".join(group[:50]),
                ])


MAP_W, MAP_H, MAP_PAD = 760, 470, 34


def short_path(url, limit=30):
    path = urllib.parse.urlparse(url).path.strip("/") or "/"
    return path if len(path) <= limit else path[:limit - 1] + "…"


def render_map_svg(pages, clusters):
    """Inline SVG content-similarity map. No script, no external anything.

    Distance means similarity, so the reader can infer clusters from position —
    which is the whole point of the picture and the one inference the layout
    actually supports.

    Identity is never colour alone: each category also has its own shape, the
    legend is always present, and the flagged pages carry direct labels. Light
    mode puts the aqua slot under 3:1 against the surface, and the palette's
    relief rule wants labels or a table for that — the report has both.
    """
    nodes, edges, neighbours = similarity_graph(pages)
    if len(nodes) < 3:
        return "", []
    flagged_urls = {u for group in clusters for u in group}

    pos = layout_force(len(nodes), edges)
    xs = [p[0] for p in pos]
    ys = [p[1] for p in pos]
    span_x = (max(xs) - min(xs)) or 1.0
    span_y = (max(ys) - min(ys)) or 1.0
    # One scale for both axes: distance must mean the same thing horizontally
    # and vertically, or the clusters are a lie.
    scale = min((MAP_W - 2 * MAP_PAD) / span_x, (MAP_H - 2 * MAP_PAD) / span_y)
    cx_off = (MAP_W - span_x * scale) / 2 - min(xs) * scale
    cy_off = (MAP_H - span_y * scale) / 2 - min(ys) * scale
    screen = [(x * scale + cx_off, y * scale + cy_off) for x, y in pos]

    def category(url):
        if url in flagged_urls:
            return "flagged"
        return "blog" if is_blog(url) else "other"

    out = ['<svg class="map" viewBox="0 0 %d %d" role="img" '
           'aria-label="Content similarity map: each mark is a page, and pages '
           'placed closer together share more vocabulary." '
           'xmlns="http://www.w3.org/2000/svg">' % (MAP_W, MAP_H)]

    out.append('<g class="map-edges">')
    for a, b, weight in edges:
        ax, ay = screen[a]
        bx, by = screen[b]
        out.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" '
                   'stroke-width="%.2f" opacity="%.2f"/>'
                   % (ax, ay, bx, by, 0.6 + weight * 1.6, 0.10 + weight * 0.35))
    out.append("</g>")

    out.append('<g class="map-nodes">')
    where = {}
    for i, page in enumerate(nodes):
        x, y = screen[i]
        where[page["url"]] = (x, y)
        kind = category(page["url"])
        title = "%s %d words" % (short_path(page["url"], 70), page["words"])
        near = neighbours.get(i) or []
        if near:
            # The tooltip carries the answer, not just a name: what this page is
            # closest to. A dot you can only identify by hovering, then hunting
            # for it in a table, is not usable information.
            title += "\nClosest: " + ", ".join(
                "%s %d%%" % (short_path(nodes[j]["url"], 32), round(s * 100))
                for s, j in near)
        title += "\nClick to open"
        # SVG <a> is native and needs no script, so every mark opens its page.
        out.append('<a href="%s" target="_blank" rel="noopener" class="n-%s">'
                   "<title>%s</title>" % (esc(page["url"]), kind, esc(title)))
        if kind == "blog":
            out.append('<rect x="%.1f" y="%.1f" width="9" height="9" rx="1.5"/>'
                       % (x - 4.5, y - 4.5))
        else:
            out.append('<circle cx="%.1f" cy="%.1f" r="%d"/>'
                       % (x, y, 7 if kind == "flagged" else 5))
        # Hover target larger than the mark; an 8px dot is not a hit area.
        out.append('<circle class="hit" cx="%.1f" cy="%.1f" r="13"/></a>' % (x, y))
    out.append("</g>")

    # One label per CLUSTER, at its centroid — never one per page. Cluster
    # members sit almost on top of each other by construction, so per-page
    # labels overprint into an unreadable smear. Learned by looking at it.
    out.append('<g class="map-labels">')
    for group in clusters:
        points = [where[u] for u in group if u in where]
        if not points:
            continue
        mx = sum(p[0] for p in points) / len(points)
        my = sum(p[1] for p in points) / len(points)
        spread = max([abs(p[0] - mx) for p in points] or [0])
        anchor = "end" if mx > MAP_W * 0.6 else "start"
        offset = spread + 15
        out.append('<text x="%.1f" y="%.1f" text-anchor="%s">'
                   "%d pages, same topic</text>"
                   % (mx + (-offset if anchor == "end" else offset),
                      my + 4, anchor, len(group)))
    out.append("</g></svg>")

    # The map answers "is there structure". This answers "what do I open next":
    # every page with its closest matches, worst offender first.
    rows = []
    for i, page in enumerate(nodes):
        near = neighbours.get(i) or []
        if near:
            rows.append({
                "url": page["url"],
                "blog": is_blog(page["url"]),
                "flagged": page["url"] in flagged_urls,
                "top": round(near[0][0] * 100),
                "matches": [(nodes[j]["url"], round(s * 100)) for s, j in near],
            })
    rows.sort(key=lambda r: -r["top"])
    return "".join(out), rows


def esc(s):
    return html.escape(str(s), quote=True)


def link_cell(url):
    short = url if len(url) <= 90 else url[:87] + "..."
    return '<a href="%s" target="_blank" rel="noopener">%s</a>' % (esc(url), esc(short))


HTML_CSS = """
:root{color-scheme:light;
--bg:#fcfcfb;--fg:#0b0b0b;--mut:#52514e;--line:#e5e7eb;--card:#f6f6f4;
--hi:#b42318;--md:#b54708;--lo:#175cd3;
--s1:#2a78d6;--s2:#eb6834;--s3:#1baf7a;--edge:#52514e;}
/* Dark is selected, not an inverted flip: the same three hues re-stepped for
   the dark surface and validated against it as a set. */
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
color-scheme:dark;
--bg:#1a1a19;--fg:#fff;--mut:#c3c2b7;--line:#33332f;--card:#232320;
--hi:#f97066;--md:#fdb022;--lo:#84caff;
--s1:#3987e5;--s2:#d95926;--s3:#199e70;--edge:#c3c2b7;}}
:root[data-theme="dark"]{color-scheme:dark;
--bg:#1a1a19;--fg:#fff;--mut:#c3c2b7;--line:#33332f;--card:#232320;
--hi:#f97066;--md:#fdb022;--lo:#84caff;
--s1:#3987e5;--s2:#d95926;--s3:#199e70;--edge:#c3c2b7;}
*{box-sizing:border-box}
body{margin:0;padding:32px 24px 64px;background:var(--bg);color:var(--fg);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;}
.wrap{max-width:1080px;margin:0 auto}
h1{font-size:26px;margin:0 0 4px}
.sub{color:var(--mut);margin:0 0 28px;font-size:14px}
.stats{display:flex;gap:28px;flex-wrap:wrap;padding:16px 20px;background:var(--card);
border:1px solid var(--line);border-radius:10px;margin-bottom:32px}
.stat b{display:block;font-size:22px;line-height:1.2}
.stat span{color:var(--mut);font-size:12px;text-transform:uppercase;letter-spacing:.04em}
details{border:1px solid var(--line);border-radius:10px;margin-bottom:12px;overflow:hidden}
details[open]{background:var(--card)}
summary{cursor:pointer;padding:14px 18px;font-weight:600;display:flex;
align-items:center;gap:12px;list-style:none}
summary::-webkit-details-marker{display:none}
summary::before{content:"\\25B8";color:var(--mut);font-size:11px;transition:transform .15s}
details[open] summary::before{transform:rotate(90deg)}
.pill{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;
padding:3px 8px;border-radius:999px;border:1px solid currentColor}
.high{color:var(--hi)}.med{color:var(--md)}.low{color:var(--lo)}
.count{margin-left:auto;color:var(--mut);font-weight:500;font-size:13px}
.blognote{color:var(--mut);font-weight:400}
.body{padding:0 18px 18px}
.fix{color:var(--mut);font-size:13.5px;margin:0 0 14px;padding-left:2px}
table{width:100%;border-collapse:collapse;font-size:13.5px}
th{text-align:left;color:var(--mut);font-weight:600;font-size:11px;
text-transform:uppercase;letter-spacing:.04em;padding:6px 10px;border-bottom:1px solid var(--line)}
td{padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top;
word-break:break-word}
tr:last-child td{border-bottom:none}
a{color:var(--lo);text-decoration:none}a:hover{text-decoration:underline}
td.num{white-space:nowrap;text-align:right}
/* -- content similarity map -- */
.mapwrap{border:1px solid var(--line);border-radius:10px;padding:14px 16px 6px;
margin-bottom:14px;background:var(--card)}
.mapwrap h2{font-size:15px;margin:0 0 2px}
.map{width:100%;height:auto;display:block;overflow:visible}
.map-edges line{stroke:var(--edge)}
.map-nodes circle,.map-nodes rect{stroke:var(--card);stroke-width:2}
.map-nodes a{cursor:pointer}
.n-flagged circle{fill:var(--s1)}
.n-blog rect{fill:var(--s2)}
.n-other circle{fill:var(--s3)}
.map-nodes .hit{fill:transparent;stroke:none}
.map-nodes a:hover circle:not(.hit),.map-nodes a:hover rect{stroke:var(--fg)}
.map-nodes a:focus-visible circle:not(.hit),.map-nodes a:focus-visible rect{
stroke:var(--fg);stroke-width:3}
.map-labels text{font-size:11px;fill:var(--fg);paint-order:stroke;
stroke:var(--card);stroke-width:3px;stroke-linejoin:round}
.legend{display:flex;gap:18px;flex-wrap:wrap;align-items:center;
font-size:12.5px;color:var(--mut);padding:4px 2px 8px}
.legend span{display:inline-flex;align-items:center;gap:7px}
.key{width:11px;height:11px;border-radius:50%;display:inline-block}
.key.sq{border-radius:2px}
.detail{color:var(--mut)}
.clean{padding:40px;text-align:center;background:var(--card);border-radius:10px;
border:1px solid var(--line)}
.more{color:var(--mut);font-size:13px;padding:10px 10px 0}
footer{margin-top:36px;color:var(--mut);font-size:12.5px;border-top:1px solid var(--line);
padding-top:16px}
@media print{summary{display:block}details{break-inside:avoid}details>.body{display:block!important}}
"""


def write_html(path, domain, findings, live, pages, elapsed, cache_size, opts,
               boiler, split=None):
    total = sum(len(findings.get(k) or []) for k, _, _, _ in ISSUES)
    stamp = time.strftime("%d %b %Y, %H:%M")

    parts = ['<!doctype html><html lang="en"><head><meta charset="utf-8">',
             '<meta name="viewport" content="width=device-width,initial-scale=1">',
             "<title>Site scan — %s</title><style>%s</style></head><body><div class='wrap'>"
             % (esc(domain), HTML_CSS)]

    parts.append("<h1>Site scan — %s</h1>" % esc(domain))
    parts.append('<p class="sub">%s &middot; raw HTML only, no JavaScript rendering</p>'
                 % esc(stamp))

    stats = [("Pages crawled", len(pages)), ("Pages parsed", len(live)),
             ("URLs verified", cache_size), ("Issues found", total)]
    if split:
        # Headline duplication figures, in the shape Siteliner reports them.
        stats += [("Duplicate content", "%s%%" % split["duplicate_pct"]),
                  ("Unique content", "%s%%" % split["unique_pct"])]
    stats.append(("Scan time", "%.0fs" % elapsed))

    parts.append('<div class="stats">')
    for label, val in stats:
        parts.append('<div class="stat"><b>%s</b><span>%s</span></div>'
                     % (esc(val), esc(label)))
    parts.append("</div>")

    topic_groups = [[r["url"]] + r.get("group", [])
                    for r in (findings.get("content_topic") or [])]
    flagged = {u for group in topic_groups for u in group}
    svg, near_rows = render_map_svg([p for p in live if is_indexable(p)],
                                    topic_groups)
    if svg:
        parts.append('<div class="mapwrap">')
        parts.append("<h2>Content similarity map</h2>")
        parts.append('<p class="sub" style="margin:0 0 6px">Each mark is a page. '
                     'Pages sitting closer together share more of their '
                     'vocabulary, and lines join each page to its nearest '
                     'matches. Tight knots are worth a look.</p>')
        parts.append('<div class="legend">')
        for cls, label, count_of in (
                ("s1", "Same-topic cluster", len(flagged)),
                ("s2", "Blog post", sum(1 for p in live if is_blog(p["url"]))),
                ("s3", "Other page", 0)):
            shape = " sq" if cls == "s2" else ""
            tail = " (%d)" % count_of if count_of else ""
            parts.append('<span><i class="key%s" style="background:var(--%s)"></i>'
                         "%s%s</span>" % (shape, cls, esc(label), tail))
        parts.append("</div>")
        parts.append(svg)
        parts.append('<p class="fix" style="padding:2px 2px 0">Every mark is a '
                     "link — click one to open that page. Hover shows what it "
                     "sits closest to.</p>")
        parts.append("</div>")

    if near_rows:
        overlapping = [r for r in near_rows if r["top"] >= 40]
        parts.append("<details%s><summary>"
                     % (" open" if any(r["flagged"] for r in near_rows[:12])
                        else ""))
        parts.append('<span class="pill low">Detail</span>')
        parts.append("<span>Closest match for every page</span>")
        parts.append('<span class="count">%d with 40%%+ overlap</span>'
                     "</summary>" % len(overlapping))
        parts.append('<div class="body">')
        parts.append('<p class="fix">Sorted by strongest match first, so the '
                     "pages most worth comparing are at the top. High overlap "
                     "is a reason to look, never a reason to merge on its "
                     "own.</p>")
        parts.append("<table><tr><th>Page</th><th>Closest matches</th>"
                     "<th>Top</th></tr>")
        for r in near_rows[:150]:
            tag = " · blog" if r["blog"] else ""
            flag = ' style="font-weight:600"' if r["flagged"] else ""
            matches = "<br>".join(
                "%s <span class='detail'>%d%%</span>" % (link_cell(u), pct)
                for u, pct in r["matches"])
            parts.append("<tr%s><td>%s<span class='detail'>%s</span></td>"
                         "<td>%s</td><td class='detail num'>%d%%</td></tr>"
                         % (flag, link_cell(r["url"]), esc(tag), matches,
                            r["top"]))
        parts.append("</table>")
        if len(near_rows) > 150:
            parts.append('<p class="more">Showing 150 of %d. Full data in the '
                         "JSON export.</p>" % len(near_rows))
        parts.append("</div></details>")

    if not total:
        parts.append('<div class="clean"><h2>Clean</h2>'
                     "<p>Nothing found across %d pages.</p></div>" % len(live))
    else:
        for key, sev, label, fix in sorted(ISSUES, key=lambda i: SEV_ORDER[i[1]]):
            rows = findings.get(key) or []
            if not rows:
                continue
            open_attr = " open" if sev == "high" and len(rows) <= 40 else ""
            parts.append("<details%s><summary>" % open_attr)
            parts.append('<span class="pill %s">%s</span>' % (sev, SEV_LABEL[sev]))
            parts.append("<span>%s</span>" % esc(label))
            total_rows, on_blog = blog_split(rows)
            tally = "%d" % total_rows
            if on_blog:
                tally += ' &middot; <span class="blognote">%d on blog</span>' % on_blog
            parts.append('<span class="count">%s</span></summary><div class="body">' % tally)
            parts.append('<p class="fix">%s</p>' % esc(fix))
            if on_blog:
                parts.append('<p class="fix"><strong>%d of these are blog posts.</strong> '
                             'Blog titles and descriptions are usually generated by the '
                             'platform rather than written per page, so they are counted '
                             'separately. The %d non-blog rows are the actionable '
                             'ones.</p>' % (on_blog, total_rows - on_blog))
            parts.append("<table><tr><th>URL</th><th>Detail</th><th>Page</th></tr>")
            for r in rows[:300]:
                kind = "blog" if r.get("blog") else ""
                parts.append("<tr><td>%s</td><td class='detail'>%s</td>"
                             "<td class='detail'>%s</td></tr>"
                             % (link_cell(r["url"]), esc(r.get("detail", "")), esc(kind)))
            parts.append("</table>")
            if len(rows) > 300:
                parts.append('<p class="more">Showing 300 of %d. Full list in the CSV.</p>'
                             % len(rows))
            parts.append("</div></details>")

    foot = ("Generated by site-scanner. Raw HTML only — pages that build their "
            "content in the browser will under-report. Duplicate-content matching "
            "ignored %d boilerplate phrases shared across the site. Image budget: "
            "%d KB (%d KB for banners)." % (boiler, opts.image_kb, opts.banner_kb))
    if split:
        foot += (" Pages are compared at %d%% similarity, the same threshold "
                 "Screaming Frog uses, and only pages Google would index are "
                 "checked. The duplicate percentage is broadly comparable to "
                 "Siteliner's; the unique percentage is not, because nav, header "
                 "and footer are stripped here rather than counted as common "
                 "content." % round(opts.dupe_ratio * 100))
    parts.append("<footer>%s</footer>" % esc(foot))
    parts.append("</div></body></html>")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))


# ---------------------------------------------------------------- driver

class NoSitemap(Exception):
    """Discovery found nothing. An exception, not an exit code, so an importing
    caller can fall back to its own inventory instead of parsing stdout."""


class Options(object):
    """Scan settings, shared by both callers.

    argparse produces these same attribute names, so a Namespace is accepted
    anywhere an Options is.
    """

    def __init__(self, limit=None, workers=6, timeout=15, image_kb=IMAGE_KB,
                 banner_kb=BANNER_KB, dupe_ratio=DUPE_RATIO, external=True,
                 out=None, json=False, exclude_blog=False, delay=CRAWL_DELAY,
                 topic_ratio=TOPIC_RATIO, include_blog_topics=False):
        self.topic_ratio = topic_ratio
        self.include_blog_topics = include_blog_topics
        self.delay = delay
        self.exclude_blog = exclude_blog
        self.limit = limit
        self.workers = workers
        self.timeout = timeout
        self.image_kb = image_kb
        self.banner_kb = banner_kb
        self.dupe_ratio = dupe_ratio
        self.external = external
        self.out = out
        self.json = json


class ScanResult(object):
    """Everything one scan produced. Reporting is deliberately not its job."""

    def __init__(self, domain, sitemap, found_urls, pages, live, findings,
                 split, boiler, elapsed, urls_verified, opts):
        self.domain = domain
        self.sitemap = sitemap
        self.found_urls = found_urls
        self.pages = pages
        self.live = live
        self.findings = findings
        self.split = split
        self.boiler = boiler
        self.elapsed = elapsed
        self.urls_verified = urls_verified
        self.opts = opts
        self.dupe_scope = {"checked": len(live), "skipped_not_indexable": 0}
        self.nearest = []       # filled by scan(); see ScanResult.evidence

    def rows(self, key):
        return self.findings.get(key) or []

    def count(self, *keys):
        return sum(len(self.rows(k)) for k in keys)

    def evidence(self):
        """Machine-readable facts, for whatever consumes this.

        Deliberately carries no severity, no recommendation prose, and no
        pass/fail. Collection and judgement are separate jobs: the thresholds
        that decide whether 42 long titles is a problem belong to the report
        that consumes this, where a non-programmer can change them, not baked
        into a crawler.
        """
        o, rows, count = self.opts, self.rows, self.count
        payload = {
            "source": "site-scanner",
            "schema": 1,
            "site": self.domain,
            "scanned_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "javascript_rendered": False,
            "crawl": {
                "sitemap": self.sitemap,
                "urls_in_sitemap": self.found_urls,
                "pages_requested": len(self.pages),
                "pages_parsed": len(self.live),
                "urls_verified": self.urls_verified,
                "limited": bool(o.limit) and self.found_urls > len(self.pages),
                "external_links_checked": bool(o.external),
                "elapsed_seconds": round(self.elapsed, 1),
            },
            "images": {
                "budget_kb": o.image_kb,
                "banner_budget_kb": o.banner_kb,
                "missing_alt_count": count("alt_missing"),
                "empty_alt_count": count("alt_empty"),
                "over_budget_count": count("image_heavy", "image_huge"),
                "over_1mb_count": count("image_huge"),
                "broken_count": count("image_broken"),
                "missing_alt": [{"src": r["url"], "pages": r.get("group", [])}
                                for r in rows("alt_missing")],
                "over_budget": [{"src": r["url"], "kb": r.get("kb"),
                                 "banner": r.get("banner", False)}
                                for r in rows("image_huge") + rows("image_heavy")],
                "broken": [{"src": r["url"]} for r in rows("image_broken")],
            },
            "links": {
                "broken_count": count("link_broken"),
                "broken_internal_count": len([r for r in rows("link_broken")
                                              if r.get("internal")]),
                "redirect_count": count("link_redirect"),
                # Rate-limited, so never confirmed either way. Deliberately a
                # separate count: a consumer that adds this to broken_count is
                # publishing "dead" about links that were merely unreachable.
                "unverified_count": count("link_unverified"),
                "broken": [{"url": r["url"], "status": r.get("status"),
                            "internal": r.get("internal", False),
                            "linked_from": r.get("group", [])}
                           for r in rows("link_broken")],
                "unverified": [{"url": r["url"], "status": r.get("status"),
                                "internal": r.get("internal", False),
                                "linked_from": r.get("group", [])}
                               for r in rows("link_unverified")],
            },
            "content": {
                "similarity_threshold": o.dupe_ratio,
                "pages_checked": self.dupe_scope["checked"],
                "pages_skipped_not_indexable":
                    self.dupe_scope["skipped_not_indexable"],
                "exact_duplicate_clusters": [
                    {"pages": [r["url"]] + r.get("group", [])}
                    for r in rows("content_exact")],
                "exact_duplicate_cluster_count": count("content_exact"),
                "duplicate_clusters": [{"pages": [r["url"]] + r.get("group", [])}
                                       for r in rows("content_duplicate")],
                "duplicate_cluster_count": count("content_duplicate"),
                # Same topic, different words. Candidates only — competition is
                # not established without a live SERP check.
                "topic_overlap_threshold": o.topic_ratio,
                "topic_cluster_count": count("content_topic"),
                "topic_clusters": [
                    {"pages": [r["url"]] + r.get("group", []),
                     "max_term_overlap_pct": r.get("value")}
                    for r in rows("content_topic")],
                "topic_overlap_method": "tf-idf cosine over body terms; "
                                        "lexical, not semantic — no synonym matching",
                # Per-page closest matches, not only the flagged clusters. A
                # consumer wants to answer "what is this page nearest to" for
                # any page, at whatever threshold it cares about.
                "nearest": self.nearest,
            },
            # Every meta count is given twice: the raw total, and the total with
            # blog posts removed. Threshold on the _excl_blog figure — blog meta
            # is generated by the platform and is not a per-page authoring
            # decision, so it does not belong in a count of things to fix.
            "meta": dict(
                [(k, count(v)) for k, v in (
                    ("title_missing", "title_missing"),
                    ("title_duplicate_groups", "title_duplicate"),
                    ("title_too_long", "title_long"),
                    ("desc_missing", "desc_missing"),
                    ("desc_duplicate_groups", "desc_duplicate"),
                    ("h1_missing", "h1_missing"),
                    ("h1_multiple", "h1_multiple"),
                    ("thin_pages", "thin"))]
                + [(k + "_excl_blog",
                    len([r for r in rows(v) if not r.get("blog")])) for k, v in (
                    ("title_missing", "title_missing"),
                    ("title_duplicate_groups", "title_duplicate"),
                    ("title_too_long", "title_long"),
                    ("desc_missing", "desc_missing"),
                    ("desc_duplicate_groups", "desc_duplicate"),
                    ("h1_missing", "h1_missing"),
                    ("h1_multiple", "h1_multiple"),
                    ("thin_pages", "thin"))]
            ),
            "pages_unreachable": count("unreachable", "page_error"),
        }
        if self.split:
            payload["content"].update(self.split)
        return payload


def scan(domain, opts=None, progress=None, verbose=False, **kw):
    """Crawl a site and run every check. Returns a ScanResult.

    The importable entry point: no printing, no files, no sys.exit. The CLI is
    one caller and a reporting pipeline is meant to be another, so this has to
    stay usable without a subprocess or a file on disk.

        from site_scan import scan
        evidence = scan("example.com", limit=200).evidence()

    progress, when given, is called as progress(stage, done, total) with stage
    "crawl" or "verify". Raises NoSitemap if discovery finds nothing.
    """
    opts = opts or Options(**kw)
    LIMITER.delay = getattr(opts, "delay", CRAWL_DELAY)
    started = time.time()
    domain = re.sub(r"^https?://", "", domain.strip()).strip("/").lower()
    site_host = domain.replace("www.", "")
    base = "https://" + domain

    urls, sitemap = collect_urls(base, verbose=verbose)
    if not urls:
        raise NoSitemap("no sitemap found for %s (tried %s)"
                        % (domain, ", ".join(SITEMAP_CANDIDATES)))
    found_urls = len(urls)
    if opts.limit:
        urls = urls[:opts.limit]

    done = [0]
    lock = threading.Lock()

    def one(u):
        pg = scan_page(u, site_host, opts)
        with lock:
            done[0] += 1
            if progress and (done[0] % 10 == 0 or done[0] == len(urls)):
                progress("crawl", done[0], len(urls))
        return pg

    with concurrent.futures.ThreadPoolExecutor(max_workers=opts.workers) as ex:
        pages = list(ex.map(one, urls))

    cache = StatusCache()
    assets = check_assets(
        pages, cache, opts,
        progress=(lambda n, t: progress("verify", n, t)) if progress else None)

    findings, live, boiler = build_findings(pages, assets, opts)
    # Duplicate checks run on indexable pages only, so the content split has to
    # measure the same set or the percentages describe a different population
    # than the clusters do.
    indexable = [p for p in live if is_indexable(p)]
    result = ScanResult(domain, sitemap, found_urls, pages, live, findings,
                        content_split(indexable), boiler, time.time() - started,
                        len(cache), opts)
    result.dupe_scope = {"checked": len(indexable),
                         "skipped_not_indexable": len(live) - len(indexable)}

    # Closest matches per page. Index against the list similarity_graph returns,
    # NOT the one passed in — it filters pages below the distinct-term floor, so
    # the indices differ and using `indexable` here mislabels every row.
    graph_nodes, _, neighbours = similarity_graph(indexable)
    result.nearest = [
        {"page": graph_nodes[i]["url"],
         "closest": [{"page": graph_nodes[j]["url"],
                      "term_overlap_pct": round(s * 100)} for s, j in near]}
        for i, near in sorted(neighbours.items())
    ]
    return result


def write_reports(result, outdir=".", want_json=False):
    """Write the HTML report, the CSV, and optionally the evidence JSON.

    Shared by the CLI and the GUI so neither can drift from the other's output.
    Returns absolute paths keyed "html", "csv", and "json".
    """
    if outdir and outdir != "." and not os.path.isdir(outdir):
        os.makedirs(outdir)
    slug = result.domain.replace(".", "-")
    # Seconds included: two scans of the same site inside one minute would
    # otherwise silently overwrite each other's report.
    stamp = time.strftime("%Y%m%d-%H%M%S")
    base = os.path.join(outdir or ".", "scan-%s-%s" % (slug, stamp))

    write_html(base + ".html", result.domain, result.findings, result.live,
               result.pages, result.elapsed, result.urls_verified, result.opts,
               result.boiler, result.split)
    write_csv(base + ".csv", result.findings)

    paths = {"html": os.path.abspath(base + ".html"),
             "csv": os.path.abspath(base + ".csv")}
    if want_json:
        with open(base + ".json", "w", encoding="utf-8") as fh:
            json.dump(result.evidence(), fh, indent=2, sort_keys=False)
        paths["json"] = os.path.abspath(base + ".json")
    return paths


def run(opts):
    announced = set()

    def prog(stage, done, total):
        # Discovery happens inside scan(), so the page count is only knowable
        # from the first progress tick. Worth printing: it tells you whether to
        # wait around before a 2,000-page crawl starts.
        if stage not in announced:
            announced.add(stage)
            if stage == "crawl":
                print("Pages to scan    : %d" % total)
                print("External links   : %s"
                      % ("checked" if opts.external else "skipped"))
                print("")
        label = "crawling" if stage == "crawl" else "verifying links and images"
        sys.stdout.write("\r  %s %d/%d" % (label, done, total))
        sys.stdout.flush()
        if done >= total:
            sys.stdout.write("\n")

    print("Site             : %s"
          % re.sub(r"^https?://", "", opts.domain.strip()).strip("/").lower())
    try:
        result = scan(opts.domain, opts, progress=prog, verbose=True)
    except NoSitemap:
        print("\nCould not find a sitemap. Tried: %s" % ", ".join(SITEMAP_CANDIDATES))
        print("Check robots.txt for a Sitemap: line pointing somewhere else.")
        return 2

    print_console(result.domain, result.findings, result.live, result.pages,
                  result.elapsed, result.urls_verified, result.split)

    paths = write_reports(result, opts.out or ".", want_json=opts.json)
    print("Report : %s" % paths["html"])
    print("CSV    : %s" % paths["csv"])
    if paths.get("json"):
        print("JSON   : %s" % paths["json"])

    high = sum(len(result.rows(k)) for k, sev, _, _ in ISSUES if sev == "high")
    return 1 if high else 0


def main():
    # Windows consoles still default to a legacy codepage; URLs with an en-dash
    # or an accent would otherwise blow up the summary print, not just look odd.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

    p = argparse.ArgumentParser(
        description="Scan a site for missing alt text, oversized images, broken links, "
                    "duplicate content, and title/H1/description problems.")
    p.add_argument("domain", help="Site to scan, e.g. example.com")
    p.add_argument("--limit", type=int, default=None, help="Only scan the first N pages")
    p.add_argument("--workers", type=int, default=6,
                   help="Concurrent requests (default 6)")
    p.add_argument("--delay", type=float, default=CRAWL_DELAY,
                   help="Seconds between requests to one host (default %.2f, "
                        "about 5/s). Raise it if the site rate-limits us."
                        % CRAWL_DELAY)
    p.add_argument("--timeout", type=int, default=15, help="Per-request timeout in seconds")
    p.add_argument("--image-kb", type=int, default=IMAGE_KB,
                   help="Flag images larger than this many KB (default %d)" % IMAGE_KB)
    p.add_argument("--banner-kb", type=int, default=BANNER_KB,
                   help="Looser budget for banner/hero images (default %d)" % BANNER_KB)
    p.add_argument("--json", action="store_true",
                   help="Also write scan-<site>-<date>.json — machine-readable "
                        "facts, no scoring")
    p.add_argument("--dupe-ratio", type=float, default=DUPE_RATIO,
                   help="Content overlap counted as duplicate, 0-1 (default %.2f)" % DUPE_RATIO)
    p.add_argument("--no-external", dest="external", action="store_false",
                   help="Skip checking outbound links (much faster)")
    p.add_argument("--topic-ratio", type=float, default=TOPIC_RATIO,
                   help="Term overlap at which two pages are flagged as the same "
                        "topic, 0-1 (default %.2f). Lower finds more." % TOPIC_RATIO)
    p.add_argument("--include-blog-topics", action="store_true",
                   help="Also compare blog posts against each other for topic "
                        "overlap (noisy — several posts on one theme is normal)")
    p.add_argument("--exclude-blog", action="store_true",
                   help="Drop blog posts from the title/description/H1 findings "
                        "entirely instead of labelling them")
    p.add_argument("--out", default=None, help="Directory to write the report into")
    p.set_defaults(external=True)
    opts = p.parse_args()

    try:
        sys.exit(run(opts))
    except KeyboardInterrupt:
        print("\nStopped.")
        sys.exit(130)


if __name__ == "__main__":
    main()
